# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"binarize_mask": "00_mask_transform.ipynb",
         "data_loader": "00_mask_transform.ipynb",
         "data_saver": "00_mask_transform.ipynb",
         "outpath_from_inpath": "00_mask_transform.ipynb",
         "check_outpath": "00_mask_transform.ipynb",
         "create_outpath": "00_mask_transform.ipynb",
         "savingpath": "00_mask_transform.ipynb",
         "mask_transform": "00_mask_transform.ipynb",
         "nifti_binarizer": "00_mask_transform.ipynb"}

modules = ["mask_transform.py"]

doc_url = "https://SRSteinkamp.github.io/simons_mask_binarizer/"

git_url = "https://github.com/SRSteinkamp/simons_mask_binarizer/tree/main/"

def custom_doc_links(name): return None
